[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set,
  # or the root directory if a base hasn’t been set.
  directory = "api/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*/index.html"
  to = "/:splat/"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301
  force = true

[[headers]]
  for = "/blog/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000
    immutable'''