import rawJson from '@/data/stateof-js-css.json';

/**
 * This file is autogenerated out from stateof-js-css-data.json file
 * 1. stateofjs-entities.json file was generated first and includes only entities with Github data (I also had to enrich it manually because some known entities like VueJS didn't have Github data).
 * 2. then I generated  stateof-js-css-data.json file and included data from both surveys StateOfJS and StateOfCSS:
 * - included only items with Usage data
 * - included only items which are listed in the stateofjs-entities.json file from step 1.
 * - merge carefully items which existed in both surveys simultaneously
 */
export interface StateOfJSItemT {
  id: string;
  name: string;
  category: string;
  repoId: string;
  usage: { year: number; value: number }[];
}

const items = rawJson as StateOfJSItemT[];

export const repoIdToDataMap = items.reduce((acc, item) => {
  acc[item.repoId.toLowerCase()] = item;
  return acc;
}, {} as Record<string, StateOfJSItemT>);
