export const ERROR_CODE_NO_GITHUB_DATA = 'NO_GITHUB_DATA';
export const ERROR_CODE_GITHUB_CONTRIBUTORS_NEEDS_PROCESSING =
  'GITHUB_CONTRIBUTORS_NEEDS_PROCESSING';
export const ERROR_CODE_GITHUB_COMMITS_NEEDS_PROCESSING =
  'GITHUB_COMMITS_NEEDS_PROCESSING';
export const ERROR_CODE_FETCH_GITHUB_REPO_FAILED =
  'ERROR_CODE_FETCH_GITHUB_REPO_FAILED';
