const libraries: [string, string, string, string, string | null][] = [
  // 3D
  ['babylonjs', 'BabylonJS/Babylon.js', '3D', 'Babylon.js', null],
  ['three', 'mrdoob/three.js', '3D', 'Three.js', null],

  // Api Mocks
  ['msw', 'mswjs/msw', 'Api Mocks', 'MSW', null],
  ['mountebank', 'bbyars/mountebank', 'Api Mocks', 'Mountebank', null],
  ['json-server', 'typicode/json-server', 'Api Mocks', 'JSON Server', null],
  [
    'wiremock-standalone',
    'Hagith/wiremock-standalone',
    'Api Mocks',
    'WireMock',
    null,
  ],
  ['miragejs', 'miragejs/miragejs', 'Api Mocks', 'Mirage', null],

  // AWS Lambda frameworks
  ['@middy/core', 'middyjs/middy', 'AWS Lambda frameworks', 'Middy', null],
  [
    '@laconia/core',
    'laconiajs/laconia',
    'AWS Lambda frameworks',
    'Laconia',
    null,
  ],
  [
    'vandium',
    'vandium-io/vandium-node',
    'AWS Lambda frameworks',
    'vandium-node',
    null,
  ],

  // Build Tools
  ['webpack', 'webpack/webpack', 'Build Tools', 'Webpack', null],
  ['rollup', 'rollup/rollup', 'Build Tools', 'Rollup', null],
  ['@parcel/core', 'parcel-bundler/parcel', 'Build Tools', 'Parcel', null],
  ['snowpack', 'snowpackjs/snowpack', 'Build Tools', 'Snowpack', null],
  ['esbuild', 'evanw/esbuild', 'Build Tools', 'Esbuild', null],

  // Charts
  ['chart.js', 'chartjs/Chart.js', 'Charts', 'Chart.js', null],
  ['d3', 'd3/d3', 'Charts', 'd3', null],
  ['plotly.js', 'plotly/plotly.js', 'Charts', 'Plotly.js', null],
  ['highcharts', 'highcharts/highcharts', 'Charts', 'Highcharts', null],
  ['recharts', 'recharts/recharts', 'Charts', 'Apache ECharts', null],
  ['echarts', 'apache/incubator-echarts', 'Charts', 'incubator-echarts', null],
  ['@amcharts/amcharts4', 'amcharts/amcharts4', 'Charts', 'amCharts 4', null],
  ['apexcharts', 'apexcharts/apexcharts.js', 'Charts', 'Apexcharts.js', null],
  ['chartist', 'gionkunz/chartist-js', 'Charts', 'Chartist.js', null],
  ['vis', 'almende/vis', 'Charts', 'Vis.js', null],
  ['nvd3', 'novus/nvd3', 'Charts', 'Nvd3', null],
  ['amcharts3', 'amcharts/amcharts3', 'Charts', 'amCharts 3', null],
  ['peity', 'benpickles/peity', 'Charts', 'Peity', null],

  // CSS Frameworks
  ['bootstrap', 'twbs/bootstrap', 'CSS Frameworks', 'Bootstrap', null],
  ['bulma', 'jgthms/bulma', 'CSS Frameworks', 'Bulma', null],
  [
    'tailwindcss',
    'tailwindlabs/tailwindcss',
    'CSS Frameworks',
    'Tailwind CSS',
    null,
  ],
  ['tachyons', 'tachyons-css/tachyons', 'CSS Frameworks', 'Tachyons', null],
  [
    'materialize-css',
    'Dogfalo/materialize',
    'CSS Frameworks',
    'MaterializeCSS',
    null,
  ],
  [
    'html5-boilerplate',
    'h5bp/html5-boilerplate',
    'CSS Frameworks',
    'HTML5 Boilerplate',
    null,
  ],
  [
    'foundation-sites',
    'foundation/foundation-sites',
    'CSS Frameworks',
    'Foundation',
    null,
  ],
  [
    'material-design-lite',
    'google/material-design-lite',
    'CSS Frameworks',
    'Material Design Lite',
    null,
  ],
  [
    'material-components-web',
    'material-components/material-components-web',
    'CSS Frameworks',
    'Material Components for the web',
    null,
  ],
  ['spectre.css', 'picturepan2/spectre', 'CSS Frameworks', 'Spectre.css', null],

  // CSS-IN-JS
  ['styled-jsx', 'vercel/styled-jsx', 'CSS-IN-JS', 'styled-jsx', 'react'],
  [
    'styled-components',
    'styled-components/styled-components',
    'CSS-IN-JS',
    'styled-components',
    'react',
  ],
  ['radium', 'formidablelabs/radium', 'CSS-IN-JS', 'Radium', 'react'],
  ['@linaria/core', 'callstack/linaria', 'CSS-IN-JS', 'Linaria', 'react'],
  ['jss', 'cssinjs/jss', 'CSS-IN-JS', 'JSS', null],
  ['aphrodite', 'Khan/aphrodite', 'CSS-IN-JS', 'Aphrodite', null],
  ['@emotion/css', 'emotion-js/emotion', 'CSS-IN-JS', 'Emotion', null],

  // Date Utilities
  ['date-fns', 'date-fns/date-fns', 'Date Utilities', 'date-fns', null],
  ['dayjs', 'iamkun/dayjs', 'Date Utilities', 'Dayjs', null],
  ['luxon', 'moment/luxon', 'Date Utilities', 'Luxon', null],
  ['moment', 'moment/moment', 'Date Utilities', 'Moment', null],
  ['fecha', 'taylorhakes/fecha', 'Date Utilities', 'Fecha', null],
  ['ms', 'vercel/ms', 'Date Utilities', 'ms', null],
  ['timeago.js', 'hustcc/timeago.js', 'Date Utilities', 'Timeago.js', null],
  ['date.js', 'MatthewMueller/date', 'Date Utilities', 'Date', null],

  // e2e testing
  ['puppeteer', 'puppeteer/puppeteer', 'e2e testing', 'Puppeteer', null],
  ['cypress', 'cypress-io/cypress', 'e2e testing', 'Cypress', null],
  ['playwright', 'Microsoft/playwright', 'e2e testing', 'Playwright', null],
  [
    'selenium-webdriver',
    'SeleniumHQ/selenium',
    'e2e testing',
    'Selenium',
    null,
  ],
  [
    'webdriverio',
    'webdriverio/webdriverio',
    'e2e testing',
    'Webdriverio',
    null,
  ],
  ['testcafe', 'DevExpress/testcafe', 'e2e testing', 'Testcafe', null],
  ['nightwatch', 'nightwatchjs/nightwatch', 'e2e testing', 'Nightwatch', null],
  ['taiko', 'getgauge/taiko', 'e2e testing', 'Taiko', null],
  ['nightmare', 'segmentio/nightmare', 'e2e testing', 'Nightmare', null],
  ['casperjs', 'casperjs/casperjs', 'e2e testing', 'Casperjs', null],
  ['slimerjs', 'laurentj/slimerjs', 'e2e testing', 'Slimerjs', null],
  ['zombie', 'assaf/zombie', 'e2e testing', 'Zombie', null],

  // Frontend Frameworks
  ['react', 'facebook/react', 'Frontend Frameworks', 'React', null],
  ['vue', 'vuejs/vue', 'Frontend Frameworks', 'Vue', null],
  ['@angular/core', 'angular/angular', 'Frontend Frameworks', 'Angular', null],
  ['svelte', 'sveltejs/svelte', 'Frontend Frameworks', 'Svelte', null],
  ['ember-source', 'emberjs/ember.js', 'Frontend Frameworks', 'Ember', null],
  ['alpinejs', 'alpinejs/alpine', 'Frontend Frameworks', 'Alpine.js', null],
  ['inferno', 'infernojs/inferno', 'Frontend Frameworks', 'Inferno', null],
  ['preact', 'preactjs/preact', 'Frontend Frameworks', 'Preact', null],
  [
    'hyperapp',
    'jorgebucaran/hyperapp',
    'Frontend Frameworks',
    'Hyperapp',
    null,
  ],
  ['riot', 'riot/riot', 'Frontend Frameworks', 'Riot', null],
  ['angular', 'angular/angular.js', 'Frontend Frameworks', 'AngularJS', null],
  [
    'backbone.marionette',
    'marionettejs/backbone.marionette',
    'Frontend Frameworks',
    'Backbone.marionette',
    null,
  ],
  ['knockout', 'knockout/knockout', 'Frontend Frameworks', 'Knockout', null],
  ['solid-js', 'ryansolid/solid', 'Frontend Frameworks', 'Solid', null],
  [
    'mithril',
    'MithrilJS/mithril.js',
    'Frontend Frameworks',
    'Mithril.js',
    null,
  ],
  [
    'aurelia-framework',
    'aurelia/framework',
    'Frontend Frameworks',
    'Aurelia',
    null,
  ],
  ['stimulus', 'stimulusjs/stimulus', 'Frontend Frameworks', 'Stimulus', null],
  ['marko', 'marko-js/marko', 'Frontend Frameworks', 'Marko', null],

  // GraphQL clients
  ['relay-runtime', 'facebook/relay', 'GraphQL clients', 'Relay', 'react'],
  [
    '@apollo/client',
    'apollographql/apollo-client',
    'GraphQL clients',
    'Apollo Client',
    'react',
  ],
  ['vue-apollo', 'Akryum/vue-apollo', 'GraphQL clients', 'Vue Apollo', 'vue'],
  [
    'svelte-apollo',
    'timhall/svelte-apollo',
    'GraphQL clients',
    'svelte-apollo',
    'svelte',
  ],
  [
    'ember-apollo-client',
    'ember-graphql/ember-apollo-client',
    'GraphQL clients',
    'ember-apollo-client',
    'ember',
  ],
  [
    'apollo-angular',
    'kamilkisiela/apollo-angular',
    'GraphQL clients',
    'Apollo Angular',
    'angular',
  ],

  // HTML Templating Engines
  ['ejs', 'mde/ejs', 'HTML Templating Engines', 'Ejs', null],
  [
    'handlebars',
    'wycats/handlebars.js',
    'HTML Templating Engines',
    'Handlebars.js',
    null,
  ],
  [
    'mustache',
    'janl/mustache.js',
    'HTML Templating Engines',
    'Mustache.js',
    null,
  ],
  ['pug', 'pugjs/pug', 'HTML Templating Engines', 'Pug', null],
  ['nunjucks', 'mozilla/nunjucks', 'HTML Templating Engines', 'Nunjucks', null],
  [
    'blueimp-tmpl',
    'blueimp/JavaScript-Templates',
    'HTML Templating Engines',
    'blueimp/JavaScript-Templates',
    null,
  ],
  ['dot', 'olado/doT', 'HTML Templating Engines', 'DoT', null],
  [
    'xtemplate',
    'xtemplate/xtemplate',
    'HTML Templating Engines',
    'Xtemplate',
    null,
  ],
  [
    'dustjs-linkedin',
    'linkedin/dustjs',
    'HTML Templating Engines',
    'Dust.js',
    null,
  ],
  ['ehtml', 'Guseyn/EHTML', 'HTML Templating Engines', 'EHTML', null],

  // Immutability
  ['immer', 'immerjs/immer', 'Immutability', 'Immer', null],
  ['immutable', 'facebook/immutable-js', 'Immutability', 'Immutable.js', null],

  // Lint Prettify
  ['eslint', 'eslint/eslint', 'Lint Prettify', 'ESLint', null],
  ['tslint', 'palantir/tslint', 'Lint Prettify', 'TSLint', null],
  ['prettier', 'prettier/prettier', 'Lint Prettify', 'Prettier', null],
  ['jshint', 'jshint/jshint', 'Lint Prettify', 'JSHint', null],
  [
    'js-beautify',
    'beautify-web/js-beautify',
    'Lint Prettify',
    'JS Beautifier',
    null,
  ],

  // Maps
  ['leaflet', 'Leaflet/Leaflet', 'Maps', 'Leaflet', null],
  ['ol', 'openlayers/openlayers', 'Maps', 'OpenLayers', null],

  // misc
  ['@nivo/core', 'plouc/nivo', 'misc', 'Nivo', null],
  ['apisauce', 'skellock/apisauce', 'misc', 'Apisauce', null],
  ['async', 'caolan/async', 'misc', 'Async', null],
  ['axios', 'axios/axios', 'misc', 'Axios', null],
  ['bluebird', 'petkaantonov/bluebird', 'misc', 'Bluebird', null],
  ['browserify', 'browserify/browserify', 'misc', 'Browserify', null],
  ['buefy', 'buefy/buefy', 'misc', 'Buefy', null],
  ['chai', 'chaijs/chai', 'misc', 'Chai', null],
  ['commander', 'tj/commander.js', 'misc', 'Commander.js', null],
  ['commitizen', 'commitizen/cz-cli', 'misc', 'Commitizen', null],
  ['classnames', 'JedWatson/classnames', 'misc', 'Classnames', null],
  ['cheerio', 'cheeriojs/cheerio', 'misc', 'Cheerio', null],
  ['core-js', 'zloirock/core-js', 'misc', 'core-js', null],
  ['debug', 'visionmedia/debug', 'misc', 'Debug', null],
  ['fp-ts', 'gcanti/fp-ts', 'misc', 'fp-ts', null],
  ['grunt', 'gruntjs/grunt', 'misc', 'Grunt', null],
  ['gulp', 'gulpjs/gulp', 'misc', 'Gulp', null],
  ['inquirer', 'SBoudrias/Inquirer.js', 'misc', 'Inquirer.js', null],
  ['jasmine-core', 'jasmine/jasmine', 'misc', 'Jasmine', null],
  ['jquery', 'jquery/jquery', 'misc', 'Jquery', null],
  ['karma', 'karma-runner/karma', 'misc', 'Karma', null],
  ['less', 'less/less.js', 'misc', 'Less.js', null],
  ['mkdirp', 'isaacs/node-mkdirp', 'misc', 'node-mkdirp', null],
  ['mocha', 'mochajs/mocha', 'misc', 'Mocha', null],
  ['node-fetch', 'bitinn/node-fetch', 'misc', 'node-fetch', null],
  ['passport', 'jaredhanson/passport', 'misc', 'Passport', null],
  ['prop-types', 'facebook/prop-types', 'misc', 'prop-types', null],
  ['protractor', 'angular/protractor', 'misc', 'Protractor', null],
  [
    'react-chartjs-2',
    'reactchartjs/react-chartjs-2',
    'misc',
    'react-chartjs-2',
    null,
  ],
  ['react-router', 'ReactTraining/react-router', 'misc', 'react-router', null],
  ['react-vis', 'uber-common/react-vis', 'misc', 'react-vis', null],
  ['sanctuary', 'sanctuary-js/sanctuary', 'misc', 'Sanctuary', null],
  ['sass', 'sass/dart-sass', 'misc', 'dart-sass', null],
  ['superagent', 'visionmedia/superagent', 'misc', 'Superagent', null],
  [
    'universal-router',
    'kriasoft/universal-router',
    'misc',
    'universal-router',
    null,
  ],
  ['uuid', 'uuidjs/uuid', 'misc', 'Uuid', null],
  ['victory', 'formidablelabs/victory', 'misc', 'Victory', null],
  ['yargs', 'yargs/yargs', 'misc', 'Yargs', null],
  ['postcss', 'postcss/postcss', 'misc', 'Postcss', null],
  [
    'create-react-app',
    'facebook/create-react-app',
    'misc',
    'Create React App',
    null,
  ],
  ['react-native', 'facebook/react-native', 'misc', 'react-native', null],
  ['electron', 'electron/electron', 'misc', 'Electron', null],
  ['animate.css', 'animate-css/animate.css', 'misc', 'Animate.css', null],
  [
    '@fortawesome/fontawesome-free',
    'FortAwesome/Font-Awesome',
    'misc',
    'Font Awesome',
    null,
  ],
  ['reveal.js', 'hakimel/reveal.js', 'misc', 'Reveal.js', null],
  ['@ionic/core', 'ionic-team/ionic', 'misc', 'Ionic', null],
  ['normalize.css', 'necolas/normalize.css', 'misc', 'Normalize.css', null],
  [
    'material-design-icons',
    'google/material-design-icons',
    'misc',
    'Material Icons',
    null,
  ],
  ['yarn', 'yarnpkg/yarn', 'misc', 'Yarn', null],
  ['serverless', 'serverless/serverless', 'misc', 'Serverless Framework', null],
  ['@babel/core', 'babel/babel', 'misc', 'Babel', null],
  ['animejs', 'juliangarnier/anime', 'misc', 'Anime', null],
  ['impress.js', 'impress/impress.js', 'misc', 'Impress.js', null],
  ['ghost', 'TryGhost/Ghost', 'misc', 'Ghost', null],
  ['mermaid', 'knsv/mermaid', 'misc', 'Mermaid', null],
  ['strapi', 'strapi/strapi', 'misc', 'Strapi', null],
  ['pixi.js', 'pixijs/pixi.js', 'misc', 'PixiJS', null],
  ['fullpage.js', 'alvarotrigo/fullPage.js', 'misc', 'fullPage.js', null],
  [
    '@atomist/hackathon-starter',
    'sahat/hackathon-starter',
    'misc',
    'Hackathon Starter',
    null,
  ],
  ['video.js', 'videojs/video.js', 'misc', 'Video.js', null],
  ['clipboard', 'zenorocha/clipboard.js', 'misc', 'clipboard.js', null],
  ['faker', 'Marak/Faker.js', 'misc', 'Faker.js', null],
  ['phaser', 'photonstorm/phaser', 'misc', 'Phaser', null],
  ['quill', 'quilljs/quill', 'misc', 'Quill', null],
  [
    'ant-design-pro',
    'ant-design/ant-design-pro',
    'misc',
    'Ant Design Pro',
    null,
  ],
  ['@vue/cli', 'vuejs/vue-cli', 'misc', 'Vue CLI', 'vue'],
  ['slick-carousel', 'kenwheeler/slick', 'misc', 'Slick', null],
  ['lerna', 'lerna/lerna', 'misc', 'Lerna', null],
  ['swiper', 'nolimits4web/Swiper', 'misc', 'Swiper', null],
  ['request', 'request/request', 'misc', 'Request', null],
  ['standard', 'standard/standard', 'misc', 'JavaScript Standard Style', null],
  ['modernizr', 'Modernizr/Modernizr', 'misc', 'Modernizr', null],
  ['whatwg-fetch', 'github/fetch', 'misc', 'Fetch', null],
  ['xlsx', 'SheetJS/sheetjs', 'misc', 'SheetJS js-xlsx', null],
  ['marked', 'markedjs/marked', 'misc', 'Marked', null],
  ['@angular/cli', 'angular/angular-cli', 'misc', 'Angular CLI', 'angular'],
  ['@uppy/core', 'transloadit/uppy', 'misc', 'Uppy', null],
  ['sequelize', 'sequelize/sequelize', 'misc', 'Sequelize', null],
  ['webtorrent', 'webtorrent/webtorrent', 'misc', 'WebTorrent', null],
  [
    'webtorrent-cli',
    'webtorrent/webtorrent-cli',
    'misc',
    'webtorrent-cli',
    null,
  ],
  ['lottie-web', 'airbnb/lottie-web', 'misc', 'Lottie for Web', null],
  ['monaco-editor', 'Microsoft/monaco-editor', 'misc', 'Monaco Editor', null],
  ['tesseract.js', 'naptha/tesseract.js', 'misc', 'Tesseract.js', null],
  ['typeorm', 'typeorm/typeorm', 'misc', 'TypeORM', null],
  ['@tabler/core', 'tabler/tabler', 'misc', 'Tabler', null],
  ['ace-builds', 'ajaxorg/ace-builds', 'misc', 'Ace', null],
  [
    'react-beautiful-dnd',
    'atlassian/react-beautiful-dnd',
    'misc',
    'react-beautiful-dnd',
    null,
  ],
  ['mongoose', 'Automattic/mongoose', 'misc', 'Mongoose', null],
  ['hammerjs', 'hammerjs/hammer.js', 'misc', 'hammer.js', null],
  ['codemirror', 'codemirror/CodeMirror', 'misc', 'CodeMirror', null],
  ['sortablejs', 'SortableJS/Sortable', 'misc', 'Sortable', null],
  ['lighthouse', 'GoogleChrome/lighthouse', 'misc', 'Lighthouse', null],
  ['@polymer/polymer', 'Polymer/polymer', 'misc', 'Polymer', null],
  ['polymer-cli', 'Polymer/tools', 'misc', 'Tools', null],
  ['husky', 'typicode/husky', 'misc', 'Husky', null],
  ['purecss', 'pure-css/pure', 'misc', 'Pure.css', null],
  ['redux-saga', 'redux-saga/redux-saga', 'misc', 'redux-saga', null],
  ['jspdf', 'MrRio/jsPDF', 'misc', 'jsPDF', null],
  [
    '@angular/material',
    'angular/components',
    'misc',
    'Material for Angular',
    null,
  ],
  [
    'react-virtualized',
    'bvaughn/react-virtualized',
    'misc',
    'react-virtualized',
    null,
  ],
  ['react-window', 'bvaughn/react-window', 'misc', 'react-window', null],
  ['dragula', 'bevacqua/dragula', 'misc', 'Dragula', null],
  ['intro.js', 'usablica/intro.js', 'misc', 'Intro.js', null],
  ['normalizr', 'paularmstrong/normalizr', 'misc', 'Normalizr', null],
  ['draft-js', 'facebook/draft-js', 'misc', 'Draft.js', null],
  ['nativescript', 'NativeScript/NativeScript', 'misc', 'NativeScript', null],
  ['feather-icons', 'feathericons/feather', 'misc', 'Feather', null],
  ['slate', 'ianstormtaylor/slate', 'misc', 'Slate', null],
  ['scrollreveal', 'jlmakes/scrollreveal', 'misc', 'Scrollreveal', null],
  ['react-motion', 'chenglou/react-motion', 'misc', 'react-motion', null],
  [
    '@mostly-adequate/support',
    'MostlyAdequate/mostly-adequate-guide',
    'misc',
    'Guide to FP',
    null,
  ],
  ['react-spring', 'drcmda/react-spring', 'misc', 'react-spring', null],
  ['autoprefixer', 'postcss/autoprefixer', 'misc', 'Autoprefixer', null],
  ['flv.js', 'Bilibili/flv.js', 'misc', 'Flv.js', null],
  ['plyr', 'sampotts/plyr', 'misc', 'Plyr', null],
  ['sharp', 'lovell/sharp', 'misc', 'Sharp', null],
  ['localforage', 'localForage/localForage', 'misc', 'localForage', null],
  ['react-use', 'streamich/react-use', 'misc', 'react-use', null],
  ['popmotion', 'Popmotion/popmotion', 'misc', 'Popmotion', null],
  [
    'react-native-web',
    'necolas/react-native-web',
    'misc',
    'React Native for Web',
    null,
  ],
  ['fabric', 'fabricjs/fabric.js', 'misc', 'Fabric.js', null],
  ['highlight.js', 'highlightjs/highlight.js', 'misc', 'Highlight.js', null],
  ['howler', 'goldfire/howler.js', 'misc', 'Howler.js', null],
  ['vue-router', 'vuejs/vue-router', 'misc', 'Vue Router', null],
  ['reselect', 'reduxjs/reselect', 'misc', 'Reselect', null],
  ['vux', 'airyland/vux', 'misc', 'Vux', null],
  ['pkg', 'zeit/pkg', 'misc', 'Pkg', null],
  ['@blueprintjs/core', 'palantir/blueprint', 'misc', 'Blueprint', 'react'],
  ['react-query', 'tannerlinsley/react-query', 'misc', 'React Query', null],
  ['validator', 'chriso/validator.js', 'misc', 'validator.js', null],
  ['flux', 'facebook/flux', 'misc', 'Flux', null],
  ['js-cookie', 'js-cookie/js-cookie', 'misc', 'JavaScript Cookie', null],
  ['ccxt', 'ccxt/ccxt', 'misc', 'Ccxt', null],
  ['velocity-animate', 'julianshapiro/velocity', 'misc', 'Velocity', null],
  [
    'angular-material',
    'angular/material',
    'misc',
    'Material for AngularJS',
    'angularjs',
  ],
  ['egg', 'eggjs/egg', 'misc', 'Egg', null],
  ['@popperjs/core', 'popperjs/popper-core', 'misc', 'Popper', null],
  ['uikit', 'uikit/uikit', 'misc', 'UIkit', null],
  ['vant', 'youzan/vant', 'misc', 'Vant', 'vue'],
  ['@mojs/core', 'mojs/mojs', 'misc', 'mojs', null],
  ['cleave.js', 'nosir/cleave.js', 'misc', 'Cleave.js', null],
  ['mint-ui', 'ElemeFE/mint-ui', 'misc', 'Mint UI', null],
  ['file-saver', 'eligrey/FileSaver.js', 'misc', 'FileSaver.js', null],
  [
    'streamsaver',
    'jimmywarting/StreamSaver.js',
    'misc',
    'StreamSaver.js',
    null,
  ],
  ['vite', 'vitejs/vite', 'misc', 'Vite', null],
  ['framework7', 'framework7io/framework7', 'misc', 'Framework7', null],
  ['trix', 'basecamp/trix', 'misc', 'Trix', null],
  ['chalk', 'chalk/chalk', 'misc', 'Chalk', null],
  ['react-admin', 'marmelab/react-admin', 'misc', 'react-admin', 'react'],
  ['coffeescript', 'jashkenas/coffeescript', 'misc', 'CoffeeScript', null],
  [
    'react-loadable',
    'thejameskyle/react-loadable',
    'misc',
    'react-loadable',
    null,
  ],
  ['ink', 'vadimdemedes/ink', 'misc', 'Ink', null],
  ['dva', 'dvajs/dva', 'misc', 'DvaJS', null],
  ['svgo', 'svg/svgo', 'misc', 'Svgo', null],
  ['jsdom', 'jsdom/jsdom', 'misc', 'Jsdom', null],
  ['aos', 'michalsnik/aos', 'misc', 'Aos', null],
  ['swr', 'vercel/swr', 'misc', 'SWR', null],
  ['ar.js', 'jeromeetienne/AR.js', 'misc', 'AR.js', null],
  ['masonry-layout', 'desandro/masonry', 'misc', 'Masonry', null],
  ['react-dnd', 'react-dnd/react-dnd', 'misc', 'React DnD', null],
  ['ionicons', 'ionic-team/ionicons', 'misc', 'Ionicons', null],
  ['rxdb', 'pubkey/rxdb', 'misc', 'RxDB', null],
  ['roughjs', 'pshihn/rough', 'misc', 'Rough.js', null],
  ['medium-editor', 'yabwe/medium-editor', 'misc', 'MediumEditor', null],
  ['q', 'kriskowal/q', 'misc', 'q', null],
  ['zepto', 'madrobby/zepto', 'misc', 'Zepto.js', null],
  ['@shopify/draggable', 'Shopify/draggable', 'misc', 'Draggable', null],
  ['p5', 'processing/p5.js', 'misc', 'P5.js', null],
  ['lazysizes', 'aFarkas/lazysizes', 'misc', 'Lazysizes', null],
  ['handsontable', 'handsontable/handsontable', 'misc', 'Handsontable', null],
  ['recompose', 'acdlite/recompose', 'misc', 'Recompose', 'react'],
  ['lowdb', 'typicode/lowdb', 'misc', 'Lowdb', null],
  ['native-base', 'GeekyAnts/NativeBase', 'misc', 'NativeBase', null],
  ['@tensorflow/tfjs', 'tensorflow/tfjs', 'misc', 'TensorFlow.js', null],
  ['xstate', 'davidkpiano/xstate', 'misc', 'Xstate', null],
  ['@editorjs/editorjs', 'codex-team/editor.js', 'misc', 'Editor.js', null],
  ['prepack', 'facebook/prepack', 'misc', 'Prepack', null],
  ['n', 'tj/n', 'misc', 'n', null],
  [
    'blessed-contrib',
    'yaronn/blessed-contrib',
    'misc',
    'blessed-contrib',
    null,
  ],
  ['blessed', 'chjj/blessed', 'misc', 'Blessed', null],
  [
    'weex-vue-render',
    'weexteam/weex-vue-render',
    'misc',
    'weex-vue-render',
    null,
  ],
  ['pouchdb', 'pouchdb/pouchdb', 'misc', 'PouchDB', null],
  ['@theia/core', 'eclipse-theia/theia', 'misc', 'Eclipse Theia', null],
  ['flatpickr', 'chmln/flatpickr', 'misc', 'Flatpickr', null],
  ['frappe-charts', 'frappe/charts', 'misc', 'Frappe Charts', null],
  ['knex', 'knex/knex', 'misc', 'knex.js', null],
  [
    'jsonwebtoken',
    'auth0/node-jsonwebtoken',
    'misc',
    'node-jsonwebtoken',
    null,
  ],
  ['vivus', 'maxwellito/vivus', 'misc', 'vivus.js', null],
  [
    '@fullcalendar/core',
    'fullcalendar/fullcalendar',
    'misc',
    'FullCalendar',
    null,
  ],
  ['nodemailer', 'nodemailer/nodemailer', 'misc', 'Nodemailer', null],
  ['react-table', 'tannerlinsley/react-table', 'misc', 'React Table', 'react'],
  ['store', 'marcuswestin/store.js', 'misc', 'Store.js', null],
  ['netlify-cms-app', 'netlify/netlify-cms', 'misc', 'Netlify CMS', null],
  ['katex', 'KaTeX/KaTeX', 'misc', 'KaTeX', null],
  ['snapsvg', 'adobe-webplatform/Snap.svg', 'misc', 'Snap.svg', null],
  ['dotenv', 'motdotla/dotenv', 'misc', 'Dotenv', null],
  ['bit-bin', 'teambit/bit', 'misc', 'Bit', null],
  ['expo-cli', 'expo/expo-cli', 'misc', 'expo-cli', null],
  ['expo', 'expo/expo', 'misc', 'Expo', null],
  [
    'react-grid-layout',
    'STRML/react-grid-layout',
    'misc',
    'React-Grid-Layout',
    'react',
  ],
  [
    'headless-recorder',
    'checkly/headless-recorder',
    'misc',
    'Headless Recorder',
    null,
  ],
  ['bootswatch', 'thomaspark/bootswatch', 'misc', 'Bootswatch', null],
  ['selectize', 'selectize/selectize.js', 'misc', 'selectize.js', null],
  ['turbolinks', 'turbolinks/turbolinks', 'misc', 'Turbolinks', null],
  ['gun', 'amark/gun', 'misc', 'Gun', null],
  [
    'super-tiny-icons',
    'edent/SuperTinyIcons',
    'misc',
    'Super Tiny Icons',
    null,
  ],
  ['grapesjs', 'artf/grapesjs', 'misc', 'GrapesJS', null],
  ['sweetalert2', 'sweetalert2/sweetalert2', 'misc', 'Sweetalert2', null],
  ['aframe', 'aframevr/aframe', 'misc', 'A-Frame', null],
  ['@toast-ui/editor', 'nhn/tui.editor', 'misc', 'TOAST UI Editor', null],
  ['react-intl', 'formatjs/formatjs', 'misc', 'React Intl', null],
  ['@vx/vx', 'hshoff/vx', 'misc', 'visx', null],
  ['paper', 'paperjs/paper.js', 'misc', 'Paper.js', null],
  ['driver.js', 'kamranahmedse/driver.js', 'misc', 'Driver.js', null],
  ['twemoji', 'twitter/twemoji', 'misc', 'Twemoji', null],
  ['n8n', 'n8n-io/n8n', 'misc', 'N8n', null],
  ['johnny-five', 'rwaldron/johnny-five', 'misc', 'johnny-five', null],
  ['gpu.js', 'gpujs/gpu.js', 'misc', 'GPU.js', null],
  [
    'react-native-navigation',
    'wix/react-native-navigation',
    'misc',
    'React Native Navigation',
    null,
  ],
  [
    'react-hot-loader',
    'gaearon/react-hot-loader',
    'misc',
    'React Hot Loader',
    null,
  ],
  ['gsap', 'greensock/GSAP', 'misc', 'GSAP', null],
  ['fuse.js', 'krisk/Fuse', 'misc', 'Fuse', null],
  [
    'verbal-expressions',
    'VerbalExpressions/JSVerbalExpressions',
    'misc',
    'JSVerbalExpressions',
    null,
  ],
  ['brain.js', 'brainjs/brain.js', 'misc', 'Brain.js', null],
  ['omi', 'Tencent/omi', 'misc', 'Omi', null],
  [
    'react-three-fiber',
    'drcmda/react-three-fiber',
    'misc',
    'react-three-fiber',
    null,
  ],
  ['shelljs', 'shelljs/shelljs', 'misc', 'ShellJS', null],
  ['smartcrop', 'jwagner/smartcrop.js', 'misc', 'smartcrop.js', null],
  ['mjml', 'mjmlio/mjml', 'misc', 'MJML', null],
  ['pell', 'jaredreich/pell', 'misc', 'Pell', null],
  ['node-red', 'node-red/node-red', 'misc', 'Node-RED', null],
  ['co', 'tj/co', 'misc', 'co', null],
  ['nanoid', 'ai/nanoid', 'misc', 'Nano ID', null],
  ['browser-sync', 'BrowserSync/browser-sync', 'misc', 'Browsersync', null],
  ['systemjs', 'systemjs/systemjs', 'misc', 'SystemJS', null],
  ['pomelo', 'NetEase/pomelo', 'misc', 'Pomelo', null],
  ['verdaccio', 'verdaccio/verdaccio', 'misc', 'Verdaccio', null],
  ['matter-js', 'liabru/matter-js', 'misc', 'Matter.js', null],
  ['redux-persist', 'rt2zz/redux-persist', 'misc', 'Redux Persist', null],
  ['virtual-dom', 'Matt-Esch/virtual-dom', 'misc', 'virtual-dom', null],
  ['markdown-it', 'markdown-it/markdown-it', 'misc', 'markdown-it', null],
  [
    'apollo-server',
    'apollographql/apollo-server',
    'misc',
    'Apollo Server',
    null,
  ],
  [
    '@assemblyscript/loader',
    'AssemblyScript/assemblyscript',
    'misc',
    'AssemblyScript',
    null,
  ],
  ['jimp', 'oliver-moran/jimp', 'misc', 'Jimp', null],
  ['jquery-ui', 'jquery/jquery-ui', 'misc', 'jQuery UI', null],
  ['raphael', 'DmitryBaranovskiy/raphael', 'misc', 'Raphael', null],
  ['supertest', 'visionmedia/supertest', 'misc', 'SuperTest', null],
  [
    'x-data-spreadsheet',
    'myliang/x-spreadsheet',
    'misc',
    'x-spreadsheet',
    null,
  ],
  ['mathjs', 'josdejong/mathjs', 'misc', 'Math.js', null],
  ['headroom.js', 'WickyNilliams/headroom.js', 'misc', 'Headroom.js', null],
  ['proton-native', 'kusti8/proton-native', 'misc', 'proton-native', null],
  ['dplayer', 'DIYgod/DPlayer', 'misc', 'DPlayer', null],
  ['tone', 'Tonejs/Tone.js', 'misc', 'Tone.js', null],
  ['stylus', 'stylus/stylus', 'misc', 'Stylus', null],
  ['crypto-js', 'brix/crypto-js', 'misc', 'crypto-js', null],
  ['mousetrap', 'ccampbell/mousetrap', 'misc', 'Mousetrap', null],
  ['@antv/g2', 'antvis/g2', 'misc', 'G2', null],
  ['@antv/g2plot', 'antvis/g2plot', 'misc', 'G2Plot', null],
  ['@swc/core', 'swc-project/swc', 'misc', 'swc', null],
  ['filepond', 'pqina/filepond', 'misc', 'Filepond', null],
  [
    'react-content-loader',
    'danilowoz/react-content-loader',
    'misc',
    'react-content-loader',
    'react',
  ],
  ['list.js', 'javve/list.js', 'misc', 'List.js', null],
  ['@mdx-js/mdx', 'mdx-js/mdx', 'misc', 'MDX', null],
  ['fx', 'antonmedv/fx', 'misc', 'fx', null],
  [
    '@fluentui/react',
    'microsoft/fluentui',
    'misc',
    'Fluent UI Web/React',
    null,
  ],
  ['nock', 'nock/nock', 'misc', 'Nock', null],
  ['botkit', 'howdyai/botkit', 'misc', 'Botkit', null],
  [
    'electron-builder',
    'electron-userland/electron-builder',
    'misc',
    'electron-builder',
    null,
  ],
  ['vue-resource', 'pagekit/vue-resource', 'misc', 'vue-resource', null],
  ['bull', 'OptimalBits/bull', 'misc', 'Bull', null],
  ['@primer/css', 'primer/css', 'misc', 'Primer CSS', null],
  ['web-vitals', 'GoogleChrome/web-vitals', 'misc', 'web-vitals', null],
  ['@vueuse/core', 'vueuse/vueuse', 'misc', 'VueUse', null],

  // NodeJS Frameworks
  ['express', 'expressjs/express', 'NodeJS Frameworks', 'Express', null],
  ['@nestjs/core', 'nestjs/nest', 'NodeJS Frameworks', 'NestJS', null],
  ['koa', 'koajs/koa', 'NodeJS Frameworks', 'Koa', null],
  ['fastify', 'fastify/fastify', 'NodeJS Frameworks', 'Fastify', null],
  ['@hapi/hapi', 'hapijs/hapi', 'NodeJS Frameworks', 'Hapi', null],
  ['sails', 'balderdashy/sails', 'NodeJS Frameworks', 'Sails', null],
  ['restify', 'restify/node-restify', 'NodeJS Frameworks', 'Restify', null],
  [
    '@feathersjs/feathers',
    'feathersjs/feathers',
    'NodeJS Frameworks',
    'Feathers',
    null,
  ],
  ['loopback', 'strongloop/loopback', 'NodeJS Frameworks', 'LoopBack 3', null],
  [
    '@loopback/core',
    'strongloop/loopback-next',
    'NodeJS Frameworks',
    'LoopBack 4',
    null,
  ],

  // NodeJS Logging
  ['log4js', 'log4js-node/log4js-node', 'NodeJS Logging', 'log4js-node', null],
  ['pino', 'pinojs/pino', 'NodeJS Logging', 'Pino', null],
  ['winston', 'winstonjs/winston', 'NodeJS Logging', 'Winston', null],
  ['morgan', 'expressjs/morgan', 'NodeJS Logging', 'Morgan', null],
  ['loglevel', 'pimterry/loglevel', 'NodeJS Logging', 'Loglevel', null],
  ['bunyan', 'trentm/node-bunyan', 'NodeJS Logging', 'Bunyan', null],

  // Node Monitoring
  [
    'prom-client',
    'siimon/prom-client',
    'Node Monitoring',
    'Prometheus client',
    null,
  ],
  [
    'express-status-monitor',
    'RafalWilinski/express-status-monitor',
    'Node Monitoring',
    'express-status-monitor',
    null,
  ],
  ['clinic', 'nearform/node-clinic', 'Node Monitoring', 'Clinic.js', null],
  [
    'appmetrics-dash',
    'RuntimeTools/appmetrics-dash',
    'Node Monitoring',
    'appmetrics-dash',
    null,
  ],

  // Node Runners
  ['forever', 'foreverjs/forever', 'Node Runners', 'Forever', null],
  ['pm2', 'Unitech/pm2', 'Node Runners', 'Pm2', null],
  ['nodemon', 'remy/nodemon', 'Node Runners', 'Nodemon', null],

  // Object Schema Validation
  ['joi', 'sideway/joi', 'Object Schema Validation', 'Joi', null],
  ['ajv', 'ajv-validator/ajv', 'Object Schema Validation', 'Ajv', null],
  ['yup', 'jquense/yup', 'Object Schema Validation', 'Yup', null],

  // React Component Libraries
  [
    '@material-ui/core',
    'mui-org/material-ui',
    'React Component Libraries',
    'Material-UI',
    null,
  ],
  [
    'antd',
    'ant-design/ant-design',
    'React Component Libraries',
    'Ant Design',
    null,
  ],
  [
    'react-bootstrap',
    'react-bootstrap/react-bootstrap',
    'React Component Libraries',
    'React Bootstrap',
    null,
  ],
  [
    'semantic-ui',
    'Semantic-Org/Semantic-UI',
    'React Component Libraries',
    'Semantic UI',
    null,
  ],
  [
    '@chakra-ui/react',
    'chakra-ui/chakra-ui',
    'React Component Libraries',
    'Chakra UI',
    null,
  ],
  [
    'reactstrap',
    'reactstrap/reactstrap',
    'React Component Libraries',
    'Reactstrap',
    null,
  ],
  [
    'evergreen-ui',
    'segmentio/evergreen',
    'React Component Libraries',
    'Evergreen',
    null,
  ],

  // React Dates
  [
    'react-datepicker',
    'Hacker0x01/react-datepicker',
    'React Dates',
    'react-datepicker',
    null,
  ],
  [
    'react-date-picker',
    'wojtekmaj/react-date-picker',
    'React Dates',
    'react-date-picker',
    null,
  ],
  ['react-dates', 'airbnb/react-dates', 'React Dates', 'react-dates', null],
  [
    'react-datetime',
    'arqex/react-datetime',
    'React Dates',
    'react-datetime',
    null,
  ],
  [
    'react-day-picker',
    'gpbl/react-day-picker',
    'React Dates',
    'react-day-picker',
    null,
  ],
  [
    'react-calendar',
    'wojtekmaj/react-calendar',
    'React Dates',
    'react-calendar',
    null,
  ],

  // React Document Head Tags
  [
    'react-helmet',
    'nfl/react-helmet',
    'React Document Head Tags',
    'React Helmet',
    null,
  ],
  [
    'react-helmet-async',
    'NYTimes/react-helmet-async',
    'React Document Head Tags',
    'react-helmet-async',
    null,
  ],

  // React Forms
  ['formik', 'formium/formik', 'React Forms', 'Formik', null],
  [
    'react-hook-form',
    'react-hook-form/react-hook-form',
    'React Forms',
    'React Hook Form',
    null,
  ],
  ['redux-form', 'redux-form/redux-form', 'React Forms', 'Redux Form', null],
  [
    'final-form',
    'final-form/final-form',
    'React Forms',
    'React Final Form',
    null,
  ],

  // Fullstack Serverless React Frameworks
  [
    'blitz',
    'blitz-js/blitz',
    'Fullstack Serverless React Frameworks',
    'Blitz',
    'react',
  ],
  [
    '@redwoodjs/core',
    'redwoodjs/redwood',
    'Fullstack Serverless React Frameworks',
    'RedwoodJS',
    'react',
  ],

  // React Native Android
  ['hermes-engine', 'facebook/hermes', 'React Native Android', 'Hermes', null],
  [
    'jsc-android',
    'react-community/jsc-android-buildscripts',
    'React Native Android',
    'jsc-android-buildscripts',
    null,
  ],
  [
    'react-native-v8',
    'Kudo/react-native-v8',
    'React Native Android',
    'react-native-v8',
    null,
  ],

  // React Unit Testing
  ['enzyme', 'airbnb/enzyme', 'React Unit Testing', 'Enzyme', null],
  [
    '@testing-library/react',
    'testing-library/react-testing-library',
    'React Unit Testing',
    'React Testing Library',
    null,
  ],

  // Runtime Types Checks
  ['io-ts', 'gcanti/io-ts', 'Runtime Types Checks', 'io-ts', null],
  ['runtypes', 'pelotom/runtypes', 'Runtime Types Checks', 'Runtypes', null],

  // Select Box
  ['downshift', 'downshift-js/downshift', 'Select Box', 'Downshift', 'react'],
  [
    'react-select',
    'JedWatson/react-select',
    'Select Box',
    'React Select',
    'react',
  ],
  ['select2', 'select2/select2', 'Select Box', 'Select2', null],
  [
    'react-autosuggest',
    'moroshko/react-autosuggest',
    'Select Box',
    'React Autosuggest',
    'react',
  ],
  [
    'react-autocomplete',
    'reactjs/react-autocomplete',
    'Select Box',
    'React Autocomplete',
    'react',
  ],
  [
    'react-virtualized-select',
    'bvaughn/react-virtualized-select',
    'Select Box',
    'React Virtualized Select',
    'react',
  ],
  [
    'react-dropdown',
    'fraserxu/react-dropdown',
    'Select Box',
    'react-dropdown',
    'react',
  ],

  // State Management
  ['redux', 'reduxjs/redux', 'State Management', 'Redux', null],
  ['mobx', 'mobxjs/mobx', 'State Management', 'MobX', null],
  ['rxjs', 'reactivex/rxjs', 'State Management', 'RxJS', null],
  ['recoil', 'facebookexperimental/recoil', 'State Management', 'Recoil', null],
  ['vuex', 'vuejs/vuex', 'State Management', 'Vuex', 'vue'],

  // Static Site Generators / JAMStack
  [
    'gatsby',
    'gatsbyjs/gatsby',
    'Static Site Generators / JAMStack',
    'Gatsby',
    'react',
  ],
  [
    'next',
    'vercel/next.js',
    'Static Site Generators / JAMStack',
    'Next.js',
    'react',
  ],
  [
    'nuxt',
    'nuxt/nuxt.js',
    'Static Site Generators / JAMStack',
    'Nuxt.js',
    'vue',
  ],
  [
    'sapper',
    'sveltejs/sapper',
    'Static Site Generators / JAMStack',
    'Sapper',
    'svelte',
  ],
  [
    '@11ty/eleventy',
    '11ty/eleventy',
    'Static Site Generators / JAMStack',
    '11ty',
    null,
  ],
  ['hexo', 'hexojs/hexo', 'Static Site Generators / JAMStack', 'Hexo', null],
  [
    '@docusaurus/core',
    'facebook/docusaurus',
    'Static Site Generators / JAMStack',
    'Docusaurus',
    'react',
  ],
  [
    'vuepress',
    'vuejs/vuepress',
    'Static Site Generators / JAMStack',
    'VuePress',
    'vue',
  ],
  [
    'docsify',
    'docsifyjs/docsify',
    'Static Site Generators / JAMStack',
    'Docsify',
    null,
  ],
  ['umi', 'umijs/umi', 'Static Site Generators / JAMStack', 'UmiJS', 'react'],
  [
    'react-static',
    'react-static/react-static',
    'Static Site Generators / JAMStack',
    'React Static',
    'react',
  ],
  [
    'gridsome',
    'gridsome/gridsome',
    'Static Site Generators / JAMStack',
    'Gridsome',
    'vue',
  ],

  // Static Types Checking
  [
    'typescript',
    'Microsoft/TypeScript',
    'Static Types Checking',
    'TypeScript',
    null,
  ],
  ['flow-bin', 'flowtype/flow-bin', 'Static Types Checking', 'Flow', null],

  // Testing-BDD-BehaviourDrivenDevelopment
  [
    '@cucumber/cucumber',
    'cucumber/cucumber-js',
    'Testing-BDD-BehaviourDrivenDevelopment',
    'Cucumber.js',
    null,
  ],
  [
    'mocha-cakes-2',
    'iensu/mocha-cakes-2',
    'Testing-BDD-BehaviourDrivenDevelopment',
    'Mocha Cakes 2',
    null,
  ],
  [
    'livedoc-mocha',
    'dotnetprofessional/LiveDoc',
    'Testing-BDD-BehaviourDrivenDevelopment',
    'LiveDoc',
    null,
  ],

  // ui dev environment
  [
    '@storybook/core',
    'storybookjs/storybook',
    'ui dev environment',
    'Storybook',
    null,
  ],
  [
    'react-styleguidist',
    'styleguidist/react-styleguidist',
    'ui dev environment',
    'React Styleguidist',
    'react',
  ],

  // Unit Tests Runner
  ['jest', 'facebook/jest', 'Unit Tests Runner', 'Jest', null],
  ['ava', 'avajs/ava', 'Unit Tests Runner', 'Ava', null],

  // Utilities
  ['lodash', 'lodash/lodash', 'Utilities', 'Lodash', null],
  ['ramda', 'ramda/ramda', 'Utilities', 'Ramda', null],
  ['underscore', 'jashkenas/underscore', 'Utilities', 'Underscore', null],
  ['rambda', 'selfrefactor/rambda', 'Utilities', 'Rambda', null],
  ['mout', 'mout/mout', 'Utilities', 'Mout', null],
  ['sugar', 'andrewplummer/Sugar', 'Utilities', 'Sugar', null],
  ['lazy.js', 'dtao/lazy.js', 'Utilities', 'Lazy.js', null],

  // Visual Regression
  ['backstopjs', 'garris/backstopjs', 'Visual Regression', 'BackstopJS', null],
  ['loki', 'oblador/loki', 'Visual Regression', 'Loki', null],
  ['gemini', 'gemini-testing/gemini', 'Visual Regression', 'Gemini', null],

  // Vue Component Libraries
  ['vuetify', 'vuetifyjs/vuetify', 'Vue Component Libraries', 'Vuetify', null],
  [
    'quasar',
    'quasarframework/quasar',
    'Vue Component Libraries',
    'Quasar',
    null,
  ],
  [
    'bootstrap-vue',
    'bootstrap-vue/bootstrap-vue',
    'Vue Component Libraries',
    'BootstrapVue',
    null,
  ],
  [
    'primevue',
    'primefaces/primevue',
    'Vue Component Libraries',
    'Primevue',
    null,
  ],
  [
    'vue-material',
    'vuematerial/vue-material',
    'Vue Component Libraries',
    'Vue Material',
    null,
  ],
  [
    'element-ui',
    'ElemeFE/element',
    'Vue Component Libraries',
    'Element UI',
    null,
  ],
  [
    'element-plus',
    'element-plus/element-plus',
    'Vue Component Libraries',
    'Element Plus',
    null,
  ],
  ['iview', 'iview/iview', 'Vue Component Libraries', 'iView', null],
  [
    'ant-design-vue',
    'vueComponent/ant-design-vue',
    'Vue Component Libraries',
    'Ant Design Vue',
    null,
  ],

  // Web Components
  ['@stencil/core', 'ionic-team/stencil', 'Web Components', 'Stencil', null],
  ['lit-element', 'Polymer/lit-element', 'Web Components', 'LitElement', null],

  // Web Sockets
  ['socket.io', 'socketio/socket.io', 'Web Sockets', 'Socket.io', null],
  ['ws', 'websockets/ws', 'Web Sockets', 'ws', null],
];

export interface CatalogLibraryT {
  repoId: string;
  category: string;
  alias: string;
  npm?: string | null;
  // TODO: don't forget to handle it
  isNpmAByProduct?: boolean | null;
  framework: string | null;
}

export const catalogRepoIdToLib = libraries.reduce(
  (acc, [npm, repoId, category, alias, framework]) => {
    acc[repoId] = { npm, repoId, category, alias, framework };
    return acc;
  },
  {} as Record<string, CatalogLibraryT>
);

// For use by npm-package api to return the correct repo for the npm package
export const catalogNpmToLib = libraries.reduce(
  (acc, [npm, repoId, category, alias, framework]) => {
    acc[npm] = { npm, repoId, category, alias, framework };
    return acc;
  },
  {} as Record<string, CatalogLibraryT>
);

export const catalogReposIdsByCategory = libraries.reduce(
  (acc, [, repoId, category]) => {
    if (!acc[category]) {
      acc[category] = [];
    }

    acc[category].push(repoId);

    return acc;
  },
  {} as Record<string, string[]>
);

export const catalogNpmNamesByCategory = libraries.reduce(
  (acc, [npm, , category]) => {
    if (!acc[category]) {
      acc[category] = [];
    }

    acc[category].push(npm);

    return acc;
  },
  {} as Record<string, string[]>
);
