type CategoryT = 'Framework' | 'Other';
type FrameworkT = 'React' | 'Vue';
interface LibDataT {
  category: CategoryT;
  framework: FrameworkT | null;
}

const libraries: [string, LibDataT][] = [
  // Frameworks
  ['react', { category: 'Framework', framework: null }],
  ['vue', { category: 'Framework', framework: null }],
  ['@angular/core', { category: 'Framework', framework: null }],
  ['svelte', { category: 'Framework', framework: null }],
  ['preact', { category: 'Framework', framework: null }],
  ['angular', { category: 'Framework', framework: null }],

  ['@cucumber/cucumber', { category: 'Other', framework: null }],
  ['@emotion/css', { category: 'Other', framework: null }],
  ['@hapi/hapi', { category: 'Other', framework: null }],
  ['@material-ui/core', { category: 'Other', framework: null }],
  ['@nestjs/core', { category: 'Other', framework: null }],
  ['@nivo/core', { category: 'Other', framework: null }],
  ['@parcel/core', { category: 'Other', framework: null }],
  ['antd', { category: 'Other', framework: null }],
  ['apexcharts', { category: 'Other', framework: null }],
  ['apisauce', { category: 'Other', framework: null }],
  ['async', { category: 'Other', framework: null }],
  ['axios', { category: 'Other', framework: null }],
  ['bootstrap', { category: 'Other', framework: null }],
  ['bluebird', { category: 'Other', framework: null }],
  ['browserify', { category: 'Other', framework: null }],
  ['buefy', { category: 'Other', framework: null }],
  ['bulma', { category: 'Other', framework: null }],
  ['bunyan', { category: 'Other', framework: null }],
  ['chai', { category: 'Other', framework: null }],
  ['chart.js', { category: 'Other', framework: null }],
  ['commander', { category: 'Other', framework: null }],
  ['classnames', { category: 'Other', framework: null }],
  ['cheerio', { category: 'Other', framework: null }],
  ['core-js', { category: 'Other', framework: null }],
  ['cypress', { category: 'Other', framework: null }],
  ['date-fns', { category: 'Other', framework: null }],
  ['d3', { category: 'Other', framework: null }],
  ['dayjs', { category: 'Other', framework: null }],
  ['debug', { category: 'Other', framework: null }],
  ['downshift', { category: 'Other', framework: null }],
  ['ejs', { category: 'Other', framework: null }],
  ['eslint', { category: 'Other', framework: null }],
  ['express', { category: 'Other', framework: null }],
  ['fastify', { category: 'Other', framework: null }],
  ['forever', { category: 'Other', framework: null }],
  ['fp-ts', { category: 'Other', framework: null }],
  ['gatsby', { category: 'Other', framework: null }],
  ['grunt', { category: 'Other', framework: null }],
  ['gulp', { category: 'Other', framework: null }],
  ['handlebars', { category: 'Other', framework: null }],
  ['highcharts', { category: 'Other', framework: null }],
  ['immer', { category: 'Other', framework: null }],
  ['inquirer', { category: 'Other', framework: null }],
  ['jasmine', { category: 'Other', framework: null }],
  ['jest', { category: 'Other', framework: null }],
  ['jshint', { category: 'Other', framework: null }],
  ['jquery', { category: 'Other', framework: null }],
  ['js-beautify', { category: 'Other', framework: null }],
  ['jss', { category: 'Other', framework: null }],
  ['karma', { category: 'Other', framework: null }],
  ['koa', { category: 'Other', framework: null }],
  ['less', { category: 'Other', framework: null }],
  ['lodash', { category: 'Other', framework: null }],
  ['log4js', { category: 'Other', framework: null }],
  ['luxon', { category: 'Other', framework: null }],
  ['mkdirp', { category: 'Other', framework: null }],
  ['mobx', { category: 'Other', framework: null }],
  ['mocha', { category: 'Other', framework: null }],
  ['moment', { category: 'Other', framework: null }],
  ['morgan', { category: 'Other', framework: null }],
  ['materialize-css', { category: 'Other', framework: null }],
  ['mustache', { category: 'Other', framework: null }],
  ['next', { category: 'Other', framework: null }],
  ['nightwatch', { category: 'Other', framework: null }],
  ['node-fetch', { category: 'Other', framework: null }],
  ['nodemon', { category: 'Other', framework: null }],
  ['nuxt', { category: 'Other', framework: null }],
  ['passport', { category: 'Other', framework: null }],
  ['pino', { category: 'Other', framework: null }],
  ['prettier', { category: 'Other', framework: null }],
  ['prop-types', { category: 'Other', framework: null }],
  ['pm2', { category: 'Other', framework: null }],
  ['plotly.js', { category: 'Other', framework: null }],
  ['pug', { category: 'Other', framework: null }],
  ['primevue', { category: 'Other', framework: null }],
  ['playwright', { category: 'Other', framework: null }],
  ['protractor', { category: 'Other', framework: null }],
  ['puppeteer', { category: 'Other', framework: null }],
  ['quasar', { category: 'Other', framework: null }],
  ['radium', { category: 'Other', framework: null }],
  ['ramda', { category: 'Other', framework: null }],
  ['react-autosuggest', { category: 'Other', framework: null }],
  ['react-bootstrap', { category: 'Other', framework: null }],
  ['react-chartjs-2', { category: 'Other', framework: null }],
  ['react-datepicker', { category: 'Other', framework: null }],
  ['react-date-picker', { category: 'Other', framework: null }],
  ['react-dates', { category: 'Other', framework: null }],
  ['react-day-picker', { category: 'Other', framework: null }],
  ['react-router', { category: 'Other', framework: null }],
  ['react-select', { category: 'Other', framework: null }],
  ['react-vis', { category: 'Other', framework: null }],
  ['reactstrap', { category: 'Other', framework: null }],
  ['recharts', { category: 'Other', framework: null }],
  ['recoil', { category: 'Other', framework: null }],
  ['redux', { category: 'Other', framework: null }],
  ['restify', { category: 'Other', framework: null }],
  ['rollup', { category: 'Other', framework: null }],
  ['rxjs', { category: 'Other', framework: null }],
  ['semantic-ui', { category: 'Other', framework: null }],
  ['sanctuary', { category: 'Other', framework: null }],
  ['sass', { category: 'Other', framework: null }],
  ['socket.io', { category: 'Other', framework: null }],
  ['superagent', { category: 'Other', framework: null }],
  ['select2', { category: 'Other', framework: null }],
  ['selenium-webdriver', { category: 'Other', framework: null }],
  ['styled-jsx', { category: 'Other', framework: null }],
  ['styled-components', { category: 'Other', framework: null }],
  ['tailwindcss', { category: 'Other', framework: null }],
  ['testcafe', { category: 'Other', framework: null }],
  ['tslint', { category: 'Other', framework: null }],
  ['underscore', { category: 'Other', framework: null }],
  ['universal-router', { category: 'Other', framework: null }],
  ['uuid', { category: 'Other', framework: null }],
  ['victory', { category: 'Other', framework: null }],
  ['vuetify', { category: 'Other', framework: null }],
  ['vuex', { category: 'Other', framework: null }],
  ['vue-material', { category: 'Other', framework: null }],
  ['webdriverio', { category: 'Other', framework: null }],
  ['webpack', { category: 'Other', framework: null }],
  ['winston', { category: 'Other', framework: null }],
  ['ws', { category: 'Other', framework: null }],
  ['yargs', { category: 'Other', framework: null }],
];

export const libsDataByName = libraries.reduce((acc, [libName, libData]) => {
  acc[libName] = libData;
  return acc;
}, {} as Record<string, LibDataT>);

export const libsNamesByCategory = libraries.reduce(
  (acc, [libName, libData]) => {
    if (!acc[libData.category]) {
      acc[libData.category] = [];
    }

    acc[libData.category].push(libName);

    return acc;
  },
  {} as Record<string, string[]>
);

export default libraries;
